Improved disk space validation
- Shows required disk space in error message
- Conditional disk requirement for NSDC

diff --git a/root/etc/e-smith/events/actions/nethserver-upgrade-txcheck b/root/etc/e-smith/events/actions/nethserver-upgrade-txcheck
--- a/root/etc/e-smith/events/actions/nethserver-upgrade-txcheck
+++ b/root/etc/e-smith/events/actions/nethserver-upgrade-txcheck
@@ -22,16 +22,23 @@
 
 shopt -s nullglob
 
+cd /var/lib/system-upgrade || exit 1
+
+if [[ ! -f package.list ]]; then
+    echo "[ERROR] could not read the package list"
+    exit 1
+fi
+
 rspace=$(rpm --queryformat='%{SIZE} %{NAME}\n' -qp $(<package.list) /var/tmp/nethserver-upgrade-tool/*.rpm | awk '{size += $1} END{print int(size/1024)+1}')
 fspace_root=$(df -P -k / | awk 'NR==2 {print $4}')
 
 if ((fspace_root < rspace)); then
-    echo "[ERROR] not enough free disk space ($rspace/$fspace_root)" 1>&2
+    echo "[ERROR] not enough free disk space (required $rspace, free $fspace_root)" 1>&2
     exit 1
 fi
 
-cd /var/lib/system-upgrade || exit 1
-[[ -f package.list ]] || exit 1
+echo "[NOTICE] required space $rspace, free space $fspace_root"
+
 rpm --nodeps --force -i --test $(<package.list) /var/tmp/nethserver-upgrade-tool/*.rpm
 if [[ $? != 0 ]]; then
     echo "[ERROR] the RPM transaction test failed" 1>&2
