Run also pre-backup-data event

diff --git a/root/etc/e-smith/events/actions/nethserver-upgrade-download b/root/etc/e-smith/events/actions/nethserver-upgrade-download
--- a/root/etc/e-smith/events/actions/nethserver-upgrade-download
+++ b/root/etc/e-smith/events/actions/nethserver-upgrade-download
@@ -43,6 +43,12 @@ if [[ $? != 0 || ! -f ${pkglist} ]]; then
     exit 1
 fi
 
+/sbin/e-smith/signal-event pre-backup-data
+if [[ $? != 0 ]]; then
+    echo "[ERROR] the pre-backup-data event failed"
+    exit 1
+fi
+
 rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-${reposet}bundle
 
 redhat-upgrade-tool --network 7 --instrepo=${reposet}-instrepo --force --enablerepo=${reposet}-\*
